version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: order-service-app
    image: "ghcr.io/cphsoftware2022/orderservice:0.2"
    depends_on:
      - db
    restart: always
    ports:
      - "7000:7001"
    environment:
      - server.port=7001
      - spring.datasource.url=jdbc:mysql://db:3306/order_service?allowPublicKeyRetrieval=True&createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&connectTimeout=1000
      - spring.datasource.username=root
      - spring.datasource.password=mypassword
      - spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      - spring.jpa.defer-datasource-initialization=true
      - spring.jpa.hibernate.ddl-auto=none
      - spring.sql.init.mode=always
      - spring.main.allow-bean-definition-overriding=true
      - graphql.servlet.corsEnabled=true
      - graphql.servlet.mapping=/graphql
      - graphql.servlet.enabled=true
      - spring.graphql.graphiql.enabled=true
      - spring.jpa.generate-ddl=true
      - spring.kafka.producer.bootstrap-servers=broker:9092
  db:
    image: mysql:latest
    container_name: db-mysql-order-service
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
#      - MYSQL_DATABASE=order_service