name: Java CI with Maven

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  RootPassword: root

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Set up MySQL
        run: docker pull mysql
      - name: Run MySQL image
        run: docker run --name my-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=$RootPassword -d mysql

      - name: Setup Kafka
        # You may pin to the exact commit or the version.
        # uses: 280780363/kafka-action@a66f129ffd34e42d6245b7e25d69e94659a1d444
        uses: 280780363/kafka-action@v1.0
        with:
          # Version of Bitnami Kafka to use
          kafka version: latest
          # Version of Bitnami Zookeeper to use
          zookeeper version: latest
          # The port of Kafka host
          kafka port: 9092
          # The port of Zookeeper host
          zookeeper port: 2181
          # Configure of auto.create.topics.enable
          auto create topic: true
          create topic: customer-order-topic

      - name: Build maven project
        run: mvn clean install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/cphsoftware2022/orderservice:0.3