name: Java CI with Maven

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  RootPassword: root

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Set up MySQL
        run: docker pull mysql

      - name: Run MySQL image
        run: docker run --name my-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=$RootPassword -d mysql

      - name: Build maven project
        run: mvn clean install

      - name: build docker image
        run: docker build . --file ./Dockerfile --tag order-service:1.0